# permissions for end users to edit chaosapplies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosapply-editor-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - chaosapplies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - chaosapplies/status
  verbs:
  - get
