# permissions for end users to edit chaosbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosbinding-editor-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - chaosbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - chaosbindings/status
  verbs:
  - get
